// Types + helpers for the Bear River Basin Monitor economics layer.
// Data is generated by model/build_bear_web.py -> public/bear_economics.json
// (a reconciled 80/20 snow/rain Monte Carlo, seed 42). Every *_per_genAF field
// scales linearly: multiply by a "water generated" quantity in AF for any total.

export type Range3 = [number, number, number]; // [p10, p50, p90]
export type Coef = { p10: number; p50: number; p90: number };

export type Benefit = {
  slug: string;
  label: string;
  short: string;
  layer: "Direct use" | "Ecological";
  beneficiary: string;
  confidence: "HIGH" | "MEDIUM" | "MED-LOW" | "LOW";
  color: string;
  y_af_per_inch: number;
  y_af_per_genAF: number;
  usd_per_inch: Range3;
  usd_per_genAF: Coef;
  unit_value: { lo: number; p50: number; hi: number; unit: string };
  mechanism: string;
  relationship: string;
  source: string;
};

export type Rollup = {
  key: string;
  label: string;
  usd_per_inch: Range3;
  usd_per_genAF: Coef;
  note: string;
};

export type PartitionRow = {
  fate: string;
  af: number;
  path: "surface" | "soil" | "groundwater" | "loss";
  value: string;
};

export type GslStream = { label: string; usd_per_inch: Range3; basis: string };

export type GslTerminal = {
  af_to_lake_per_inch: number;
  af_to_lake_per_genAF: number;
  share_of_inch_pct: number;
  share_of_streamflow_pct: number;
  usd_per_inch: Range3;
  usd_per_genAF: Coef;
  streams: GslStream[];
  honesty: string;
};

export type BearEcon = {
  meta: { model: string; n_draws: number; seed: number; note: string };
  basin: {
    drainage_area_sqmi: number;
    area_acres: number;
    acre_feet_per_inch: number;
    snow_frac: number;
    gross_snow_af: number;
    gross_rain_af: number;
    runoff_snow: string;
    runoff_rain: string;
    blended_runoff_p50: number;
    streamflow_af_per_inch: number;
    streamflow_af_per_genAF: number;
  };
  partition: PartitionRow[];
  benefits: Benefit[];
  rollups: Rollup[];
  gsl_terminal: GslTerminal;
  presets: { seeding_generated_af: number; quarter_inch_af: number; one_inch_af: number };
};

// ---- path colors (where the water physically goes) ----
export const PATH_COLOR: Record<string, string> = {
  surface: "#1f6f8b", // blue — river / runoff
  soil: "#0f7b54", // green — soil moisture / ET
  groundwater: "#b88a1e", // amber — recharge
  loss: "#b9c4bb", // grey — sublimation / loss
};

// ---- confidence tiers ----
export const CONF_COLOR: Record<string, string> = {
  HIGH: "#0f7b54",
  MEDIUM: "#1f6f8b",
  "MED-LOW": "#b88a1e",
  LOW: "#c0612e",
};
export const CONF_LABEL: Record<string, string> = {
  HIGH: "high confidence",
  MEDIUM: "medium confidence",
  "MED-LOW": "med-low confidence",
  LOW: "low confidence",
};

// ---- formatting ----
export function fmtUSD(n: number): string {
  if (n === undefined || n === null || isNaN(n)) return "—";
  const a = Math.abs(n);
  if (a >= 1e9) return `$${(n / 1e9).toLocaleString(undefined, { maximumFractionDigits: 2 })}B`;
  if (a >= 1e6) return `$${(n / 1e6).toLocaleString(undefined, { maximumFractionDigits: 1 })}M`;
  if (a >= 1e3) return `$${(n / 1e3).toLocaleString(undefined, { maximumFractionDigits: 0 })}K`;
  return `$${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
}
export function fmtAF(n: number): string {
  if (n === undefined || n === null || isNaN(n)) return "—";
  const a = Math.abs(n);
  if (a >= 1e6) return `${(n / 1e6).toLocaleString(undefined, { maximumFractionDigits: 2 })}M`;
  if (a >= 1e3) return `${(n / 1e3).toLocaleString(undefined, { maximumFractionDigits: 1 })}K`;
  return `${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
}
export function fmtNum(n: number, d = 0): string {
  if (n === undefined || n === null || isNaN(n)) return "—";
  return Number(n).toLocaleString(undefined, { maximumFractionDigits: d, minimumFractionDigits: d });
}

// scale a per-genAF coefficient set to absolute dollars at a chosen generated-water quantity
export function scaleCoef(c: Coef, genAF: number): Range3 {
  return [c.p10 * genAF, c.p50 * genAF, c.p90 * genAF];
}
