// Types + helpers for the Bear River Basin Monitor economics layer.
// Data is generated by model/build_bear_web.py -> public/bear_economics.json
// (a reconciled 80/20 snow/rain Monte Carlo, seed 42). Every *_per_genAF field
// scales linearly: multiply by a "water generated" quantity in AF for any total.

export type Range3 = [number, number, number]; // [p10, p50, p90]
export type Coef = { p10: number; p50: number; p90: number };

// a footnoted source: n is the in-text marker, label is the citation, url is the direct link
export type Citation = { n: number; label: string; url: string };

// a non-dollar "natural unit" for a use (tons of hay, fish, MWh, ...).
// stat_per_genAF scales linearly with the water slider, like the dollar coefficients.
export type OnGround = {
  unit_label: string;
  per_af: number;
  stat_per_genAF: number;
  blurb: string;
  confidence: "HIGH" | "MEDIUM" | "MED-LOW" | "LOW";
  source: string;
  source_url: string;
  sec_label?: string;
  sec_per_af?: number;
  sec_per_genAF?: number;
  math?: string; // plain-language derivation of the stat (may contain \n\n paragraph breaks)
};

// a real, sourced person who lives this use of the water — what drives them beyond price
export type Person = {
  name: string;
  role: string;
  org: string;
  drives: string;
  source: string;
  source_url: string;
};

export type Benefit = {
  slug: string;
  label: string;
  short: string;
  layer: "Direct use" | "Ecological";
  beneficiary: string;
  confidence: "HIGH" | "MEDIUM" | "MED-LOW" | "LOW";
  color: string;
  y_af_per_inch: number;
  y_af_per_genAF: number;
  usd_per_inch: Range3;
  usd_per_genAF: Coef;
  unit_value: { lo: number; p50: number; hi: number; unit: string };
  mechanism: string;
  relationship: string;
  source: string;
  // PhD-level enrichment (optional — present for all eight core benefits)
  dissertation?: string; // the relationship, in depth; may contain [n] footnote markers
  derivation?: string; // how the number + linear coefficient were derived
  citations?: Citation[]; // footnotes referenced by [n] markers, listed at page bottom
  on_ground?: OnGround; // a non-dollar way to feel the value (scales with the slider)
  person?: Person; // a real, sourced person whose stake in the water this is
};

export type Rollup = {
  key: string;
  label: string;
  usd_per_inch: Range3;
  usd_per_genAF: Coef;
  note: string;
};

export type PartitionRow = {
  fate: string;
  af: number;
  path: "surface" | "soil" | "groundwater" | "loss";
  value: string;
};

export type GslStream = { label: string; usd_per_inch: Range3; basis: string };

export type GslTerminal = {
  af_to_lake_per_inch: number;
  af_to_lake_per_genAF: number;
  share_of_inch_pct: number;
  share_of_streamflow_pct: number;
  usd_per_inch: Range3;
  usd_per_genAF: Coef;
  streams: GslStream[];
  honesty: string;
};

export type BearEcon = {
  meta: { model: string; n_draws: number; seed: number; note: string };
  basin: {
    drainage_area_sqmi: number;
    area_acres: number;
    acre_feet_per_inch: number;
    snow_frac: number;
    gross_snow_af: number;
    gross_rain_af: number;
    runoff_snow: string;
    runoff_rain: string;
    blended_runoff_p50: number;
    streamflow_af_per_inch: number;
    streamflow_af_per_genAF: number;
  };
  partition: PartitionRow[];
  benefits: Benefit[];
  rollups: Rollup[];
  gsl_terminal: GslTerminal;
  presets: { seeding_generated_af: number; quarter_inch_af: number; one_inch_af: number };
  methodology_note?: string;
};

// Render a string containing [n] footnote markers into React-friendly parts.
// Returns an array of strings and { marker } objects so a component can map them
// to <sup> links. Kept here so every page renders footnotes identically.
export function splitFootnotes(text: string): Array<string | { marker: number }> {
  const parts: Array<string | { marker: number }> = [];
  const re = /\[(\d+)\]/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    if (m.index > last) parts.push(text.slice(last, m.index));
    parts.push({ marker: Number(m[1]) });
    last = m.index + m[0].length;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

// ---- path colors (where the water physically goes) ----
export const PATH_COLOR: Record<string, string> = {
  surface: "#1f6f8b", // blue — river / runoff
  soil: "#0f7b54", // green — soil moisture / ET
  groundwater: "#b88a1e", // amber — recharge
  loss: "#b9c4bb", // grey — sublimation / loss
};

// ---- confidence tiers ----
export const CONF_COLOR: Record<string, string> = {
  HIGH: "#0f7b54",
  MEDIUM: "#1f6f8b",
  "MED-LOW": "#b88a1e",
  LOW: "#c0612e",
};
export const CONF_LABEL: Record<string, string> = {
  HIGH: "high confidence",
  MEDIUM: "medium confidence",
  "MED-LOW": "med-low confidence",
  LOW: "low confidence",
};

// ---- formatting ----
export function fmtUSD(n: number): string {
  if (n === undefined || n === null || isNaN(n)) return "—";
  const a = Math.abs(n);
  if (a >= 1e9) return `$${(n / 1e9).toLocaleString(undefined, { maximumFractionDigits: 2 })}B`;
  if (a >= 1e6) return `$${(n / 1e6).toLocaleString(undefined, { maximumFractionDigits: 1 })}M`;
  if (a >= 1e3) return `$${(n / 1e3).toLocaleString(undefined, { maximumFractionDigits: 0 })}K`;
  return `$${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
}
export function fmtAF(n: number): string {
  if (n === undefined || n === null || isNaN(n)) return "—";
  const a = Math.abs(n);
  if (a >= 1e6) return `${(n / 1e6).toLocaleString(undefined, { maximumFractionDigits: 2 })}M`;
  if (a >= 1e3) return `${(n / 1e3).toLocaleString(undefined, { maximumFractionDigits: 1 })}K`;
  return `${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
}
export function fmtNum(n: number, d = 0): string {
  if (n === undefined || n === null || isNaN(n)) return "—";
  return Number(n).toLocaleString(undefined, { maximumFractionDigits: d, minimumFractionDigits: d });
}

// scale a per-genAF coefficient set to absolute dollars at a chosen generated-water quantity
export function scaleCoef(c: Coef, genAF: number): Range3 {
  return [c.p10 * genAF, c.p50 * genAF, c.p90 * genAF];
}

// format a natural-unit count: small values keep a decimal, large values get commas
export function fmtStat(n: number): string {
  if (n === undefined || n === null || isNaN(n)) return "—";
  const a = Math.abs(n);
  if (a >= 1e6) return `${(n / 1e6).toLocaleString(undefined, { maximumFractionDigits: 2 })} million`;
  if (a < 10) return n.toLocaleString(undefined, { maximumFractionDigits: 1 });
  return Math.round(n).toLocaleString();
}
